---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deployment-helm-angular
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: angular-helm
  values:
    image:
      repository: haroldo89/front-app
      tag: "69"
    replicaCount: 1
    service:
      nodePort: 32200
      port: 80
      targetPort: 80
      type: NodePort

