apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-angular-production
  # namespace: ns-angular-regular-production
spec:
  rules:
  -  http:
       paths:
         - pathType: Prefix
           path: "/" 
           backend:
             service:
               name: service-angular-production