apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: angular-regular-staging
resources:
  - namespace.yaml
  - ../../base/angular-regular
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml
