apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-python-regular-production
resources:
  - namespace.yaml
  - ../../base/python-rest-api
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml
